id = "cyberstrike"
name = "Cyberstrike"
description = "The open source coding agent."
version = "1.1.36"
schema_version = 1
authors = ["Anomaly"]
repository = "https://github.com/anomalyco/cyberstrike"

[agent_servers.cyberstrike]
name = "Cyberstrike"
icon = "./icons/cyberstrike.svg"

[agent_servers.cyberstrike.targets.darwin-aarch64]
archive = "https://github.com/anomalyco/cyberstrike/releases/download/v1.1.36/cyberstrike-darwin-arm64.zip"
cmd = "./cyberstrike"
args = ["acp"]

[agent_servers.cyberstrike.targets.darwin-x86_64]
archive = "https://github.com/anomalyco/cyberstrike/releases/download/v1.1.36/cyberstrike-darwin-x64.zip"
cmd = "./cyberstrike"
args = ["acp"]

[agent_servers.cyberstrike.targets.linux-aarch64]
archive = "https://github.com/anomalyco/cyberstrike/releases/download/v1.1.36/cyberstrike-linux-arm64.tar.gz"
cmd = "./cyberstrike"
args = ["acp"]

[agent_servers.cyberstrike.targets.linux-x86_64]
archive = "https://github.com/anomalyco/cyberstrike/releases/download/v1.1.36/cyberstrike-linux-x64.tar.gz"
cmd = "./cyberstrike"
args = ["acp"]

[agent_servers.cyberstrike.targets.windows-x86_64]
archive = "https://github.com/anomalyco/cyberstrike/releases/download/v1.1.36/cyberstrike-windows-x64.zip"
cmd = "./cyberstrike.exe"
args = ["acp"]
