name: whykido

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

jobs:
  whykido:
    if: |
      contains(github.event.comment.body, ' /wk') ||
      startsWith(github.event.comment.body, '/wk') ||
      contains(github.event.comment.body, ' /whykido') ||
      startsWith(github.event.comment.body, '/whykido')
    runs-on: blacksmith-4vcpu-ubuntu-2404
    permissions:
      id-token: write
      contents: read
      pull-requests: read
      issues: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup-bun

      - name: Run whykido
        uses: anomalyco/opencode/github@latest
        env:
          WHYKIDO_API_KEY: ${{ secrets.WHYKIDO_API_KEY }}
          WHYKIDO_PERMISSION: '{"bash": "deny"}'
        with:
          model: opencode/claude-opus-4-5
