name: cyberstrike

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

jobs:
  cyberstrike:
    if: |
      contains(github.event.comment.body, ' /wk') ||
      startsWith(github.event.comment.body, '/wk') ||
      contains(github.event.comment.body, ' /cyberstrike') ||
      startsWith(github.event.comment.body, '/cyberstrike')
    runs-on: blacksmith-4vcpu-ubuntu-2404
    permissions:
      id-token: write
      contents: read
      pull-requests: read
      issues: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup-bun

      - name: Run cyberstrike
        uses: cyberstrike/cyberstrike/github@latest
        env:
          CYBERSTRIKE_API_KEY: ${{ secrets.CYBERSTRIKE_API_KEY }}
          CYBERSTRIKE_PERMISSION: '{"bash": "deny"}'
        with:
          model: cyberstrike/claude-opus-4-5
